global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:8000"]

# global:
#   scrape_interval: 15s # fréquence à laquelle Prometheus va interroger endpoint /metrics.

# scrape_configs:
#   - job_name: 'backend'
#     metrics_path: "/metrics"
#     static_configs:
#       # - targets: ['host.docker.internal:8000']
#       - targets: ["backend:8000"]  # nom du service Docker ou localhost en local
#       #le port où FastAPI expose /metrics (8000 dans mon cas).

# scrape_configs:
#   - job_name: "backend"
#     metrics_path: "/metrics"
#     static_configs:
#       - targets: ["backend:8000"]
